### ISSUE TITLE
Error while Publishing the App to the Appstore

### ISSUE THREAD

**Issue by DharmeshRathod712** [appcelerator-developer-relations/appc-sample-ios-push-notifications#1]
When I try to publish the build to App Store I get below error. 
`Invalid Bundle. The bundle at '.app/PlugIns/testapp.appex' contains disallowed file 'Frameworks'.` 
Below are the solution which I tried and corresponding results.

For the Extension app: `Embedded Content Contains Swift Code: YES`. For the extension: `Embedded Content Contains Swift Code: NO`.
Reference: https://stackoverflow.com/a/25789145
Result: Same Error

Added the Run Script code in Native Extension Project for Target Extension
`cd "${CONFIGURATION_BUILD_DIR}/${UNLOCALIZED_RESOURCES_FOLDER_PATH}/"
if [[ -d "Frameworks" ]]; then 
rm -fr Frameworks
fi`
Reference: https://stackoverflow.com/a/33092433
Result: Unable to Build the App in Appcelerator Studio. Execution stops after
`[INFO] :   Initializing the build directory  
[INFO] :   JavaScript files need to be encrypted
[INFO] :   Creating Xcode project`

Setup details: Ti SDK : 7.1.1.GA
Ti CLI : 5.0.14
Node.js Version : 8.9.1
npm Version : 5.5.1
OS : Mac OS X. 

I don't understand what is the problem.

**Comment by hansemannn** [comment]
You need SDK 7.3.0 (beta) and later as stated in the readme. The error in general describes an issue that occurs when using embedded frameworks in extensions, but I am not sure how to apply that to Titanium right now. Keeping the issue open for now.

**EDIT**: You could fix it by adding your run-script phase described above to the **extension target**, not the Titanium target. To do so, you can write a plugin-hook that hacks into the run-script-phase of the extension and place it to your application.

**EDIT 2**: No plugin hook required, you can just add it to the extension target via Xcode. Done so via https://github.com/appcelerator-developer-relations/appc-sample-ios-push-notifications/commit/0cec2f6d3f4f9b73554e11ab453913b69fe69f31, so download it again and try it out.

**NOTE**: This sample should not be submitted to the App Store in general, since it won't be accepted by Apple anyway (no sample apps allowed there).

**Comment by DharmeshRathod712** [comment]
I think SDK version should not cause any problem because even on SDK 7.1.1.GA I am able to receive the Notification (Development environment). It only causes the problem while submitting the app to Appstore. Also to test this scenario I will have to re-integrate it in My project and try to Submit it to App store as I am currently using Objective-C version of Notification Extension. :)

**Comment by hansemannn** [comment]
Closing in that case, since the demo uses Swift which is handled differently.
